name: nextflow-fastp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp=0.19.6
  - multiqc=1.7
  - jq=1.6
  - r-base=4.0.2
  - bioconductor-seqtools=1.22.0
  - r-writexl=1.3.1
  - r-kableextra=1.2.1
  - r-rmarkdown=2.3
  - r-knitr=1.29
  - r-dplyr=1.0.2
  - r-rcpproll=0.3.0